# Generated by Django 6.0.2 on 2026-02-26 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('catalogue', models.CharField(choices=[('COLLECT', 'Collection'), ('MOTCLE', 'Mots-clés'), ('EDITORS', 'Editeurs'), ('MP3', 'Audio'), ('MP4', 'Videos'), ('EBOOKS', 'E-books'), ('SUJETS', 'Sujets/Matiere')], default='e-book', max_length=50)),
                ('fichier_pdf', models.FileField(upload_to='livres_pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
