# Generated by Django 6.0.2 on 2026-02-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='catalogue',
            field=models.CharField(choices=[('COLLECT', 'Collection'), ('MOTCLE', 'Mots-clés'), ('EDITORS', 'Editeurs'), ('MP3', 'Audio'), ('MP4', 'Videos'), ('EBOOKS', 'E-books'), ('SUJETS', 'Sujets/Matiere')], default='EBOOKS', max_length=50),
        ),
    ]
