# Generated by Django 6.0.2 on 2026-02-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_livre_catalogue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='fichier_pdf',
        ),
    ]
