# Generated by Django 6.0.2 on 2026-02-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_categorie_remove_livre_catalogue_livre_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
