# Generated by Django 6.0.2 on 2026-02-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_categorie_created_alter_categorie_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='fichier_pdf',
            field=models.FileField(blank=True, null=True, upload_to='livres_pdfs/'),
        ),
    ]
