# Generated by Django 6.0.2 on 2026-03-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_livre_fichier_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='image_couverture',
            field=models.ImageField(blank=True, null=True, upload_to='couverture/'),
        ),
    ]
