# Generated by Django 6.0.2 on 2026-03-02 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_livre_image_couverture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='image_couverture',
        ),
    ]
