# Generated by Django 6.0.2 on 2026-03-03 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_livre_image_couverture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
