# Generated by Django 6.0.2 on 2026-03-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='book_cover',
            field=models.ImageField(blank=True, null=True, upload_to='livres_cover/'),
        ),
    ]
